apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  serviceName: {}
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - env: []
        image: jenkins/jenkins:lts
        imagePullPolicy: IfNotPresent
        livenessProbe: {}
        name: jenkins
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
        - containerPort: 50000
          name: jnlp-port
          protocol: TCP
        readinessProbe: {}
        resources:
          limits:
            cpu: 750m
            memory: 2000Mi
          requests:
            cpu: 700m
            memory: 1000Mi
        volumeMounts: []
      volumes: []
  volumeClaimTemplates: {}
