apiVersion: argoproj.io/v1alpha1     # for versions before 1.9.0 use apps/v1beta2
kind: Rollout
metadata:
  name: nginx
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: {duration: 300s}
  selector:
    matchLabels:
      app: nginx        # tells deployment to run 1 pods matching the template
  template:            # create pods using pod definition in this template
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:     
            requests:
              memory: 50Mi
              cpu: "50m"
            limits:
              memory: 100Mi
              cpu: "100m"
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5        
        volumeMounts:
          - name: nginx-vol
            mountPath: /etc/nginx/conf.d
          - name: nginx-vol
            mountPath: /etc/nginx/certs
      volumes:
        - name: nginx-vol
          persistentVolumeClaim:
            claimName: nginx-pvc  

